name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - docs-build
      - wheel-build-nx-cugraph
      - wheel-tests-nx-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@python-3.12
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@python-3.12
    with:
      enable_check_generated_files: false
  conda-notebook-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@python-3.12
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:cuda11.8.0-ubuntu22.04-py3.10"
      run_script: "ci/test_notebooks.sh"
  docs-build:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@python-3.12
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:cuda11.8.0-ubuntu22.04-py3.10"
      run_script: "ci/build_docs.sh"
  wheel-build-nx-cugraph:
    needs: wheel-tests-pylibcugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@python-3.12
    with:
      build_type: pull-request
      script: ci/build_wheel_nx-cugraph.sh
  wheel-tests-nx-cugraph:
    needs: wheel-build-nx-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@python-3.12
    with:
      build_type: pull-request
      script: ci/test_wheel_nx-cugraph.sh
